apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: terasky-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: terasky-backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
